services:
  frontend:
    image: idb-jovem-frontend:latest
    container_name: idb-jovem-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
